<?php

/**
 * Created by PhpStorm.
 * User: imaginato
 * Date: 17-7-31
 * Time: 上午11:18
 */
class Tutorial_HelloCustomer_Model_HelloCustomer extends Mage_Core_Model_Abstract {
    public function _construct() {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hellocustomer/helloCustomer');
    }
}