<?php

/**
 * Created by PhpStorm.
 * User: imaginato
 * Date: 17-7-31
 * Time: 下午12:22
 */
class Tutorial_HelloCustomer_Model_Mysql4_HelloCustomer_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract {
    public function _construct() {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('hellocustomer/hellocustomer');
    }
}