<?php

/**
 * Created by PhpStorm.
 * User: imaginato
 * Date: 17-8-8
 * Time: 上午10:07
 */
class Magentostudy_News_Model_News extends Mage_Core_Model_Abstract
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('magentostudy_news/news');
    }

    protected function _beforeSave()
    {
        parent::_beforeSave();
        if($this->isObjectNew())
        {
            $this->setData('created_at', Varien_Date::now());
        }
        return $this;
    }
}